name: Terraform Plan and Apply

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        env:
          TF_VAR_rds_password: ${{ secrets.TF_VAR_rds_password }}
        run: terraform plan

      - name: Terraform Apply
        env:
          TF_VAR_rds_password: ${{ secrets.TF_VAR_rds_password }}
        run: terraform apply -auto-approve